using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Models
{

    //tinfo200:[2021-03-11-<meeras4>-dykstra2] - Course class created for CourseID property in Enrollment class
    public class Course
    {
        //tinfo200:[2021-03-11-<meeras4>-dykstra2] - Course ID not to be generated by the database. 
        [DatabaseGenerated(DatabaseGeneratedOption.None)]

        //tinfo200:[2021-03-11-<meeras4>-dykstra2] - Create get & set methods for the requirements of the Course entity
        public int CourseID { get; set; }  //tinfo200:[2021-03-04-<huskyID>-dykstra2] - Course ID is the primary key of class Course
        public string Title { get; set; }
        public int Credits { get; set; }

        //tinfo200:[2021-03-11-<meeras4>-dykstra2] - Create ICollection Enrollments property. This is a navigation property that will hold more code of the enrollment entity in this Course class
        public ICollection<Enrollment> Enrollments { get; set; }
        }
    }

